# .github/workflows/pr-kicad-diff.yaml
name: KiCad Pull Request Diff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  kiri-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Kiri
        uses: usa-reddragon/kiri-github-action@v2
        with:
          # <-- Upewnij się, że ta ścieżka jest dokładnie taka, jak w repozytorium
          project-file: kicad/MyProject.kicad_pro
          # <-- jawnie ustaw folder dla artefaktów
          output-dir: kiri-output
          archive: true
          remove: false

      - name: Upload Kiri artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kiri-diff-artifacts
          path: kiri-output
